language: java

jdk:
  - oraclejdk8

install: true
before_install:
  - chmod +x travis/*.sh
  - chmod +x gradlew
script: ./travis/install.sh
env:
  global:
    - PUBLISH_BRANCH="mvn-repo"
    - DEPLOY_KEY_ID="1645300b04d0"

deploy:
  provider: releases
  api_key: "$GITHUB_API_TOKEN"
  skip_cleanup: true
  on:
    tags: true
  file:
    - "build/repo/argelbargel/jenkins/plugins/jenkins-modules-plugin/$TRAVIS_TAG/jenkins-modules-plugin-$TRAVIS_TAG.hpi"
    - "build/repo/argelbargel/jenkins/plugins/jenkins-modules-plugin/$TRAVIS_TAG/jenkins-modules-plugin-$TRAVIS_TAG.hpi.md5"
    - "build/repo/argelbargel/jenkins/plugins/jenkins-modules-plugin/$TRAVIS_TAG/jenkins-modules-plugin-$TRAVIS_TAG.hpi.sha1"
cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/native
  - $HOME/.gradle/wrapper
